<?php

$title = "Excluir Ação";
$url = $this->url('carteira', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Você tem certeza que quer deletar a ação <?= $this->escapeHtml( $carteira->codigo ) ?>? 
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= $carteira->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Sim">
        <input type="submit" class="btn btn-success" name="del" value="Não">
    </div>
</form>